name: cytoverse-ci

on:
  push:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  rcheck:
    runs-on: ubuntu-latest
#     container: r-base
    steps:
      - uses: actions/checkout@v2

#       - name: Cache pkgA
#         uses: actions/cache@v2
#         env:
#           cache-name: cache-pkgA
#         with:
#           # npm cache files are stored in `~/.npm` on Linux/macOS
#           path: /usr/local/lib/R/site-library/pkgA
#           key: ${{ runner.os }}-rcheck-${{ env.cache-name }}-${{ hashFiles('./**') }}

      - name: install packages
        id: cytolib
#         if: steps.cache-pkgA.output.cache-hit != 'true'
        run: |
          R CMD INSTALL ..
        shell: bash

      - name: Check flowWorkspace
        if: always()
#         if: steps.cache-pkgA.output.cache-hit != 'true'
        id: flowWorkspace
        run: |
          echo 'dd'
        shell: bash
      
      
