name: cytoverse-ci

on:
  push:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  rcheck:
    runs-on: ubuntu-latest
    steps:
      - name : generate gs
        run: |
          mkdir gs
          cd gs
          echo 'test' >> t.txt
          echo 'tmp_gs_dir=gs' >> $GITHUB_ENV
      - name: Upload the test gs as the artifact
        uses: 'actions/upload-artifact@v2'
        with:
            name: my-artifact
            path: ${{ env.tmp_gs_dir }}
  
#   test-open-source:
#       runs-on: [self-hosted, macox, coloc]

#       # Steps represent a sequence of tasks that will be executed as part of the job
#       steps:
#         - name: Download the test gs from the artifact
#           uses: actions/download-artifact@v2
#             with:
#               name: my-artifact
#               path: /tmp/gs

#         - name: Run the R tests against the test gs
#           run: |
#             BiocManager::install(c("cytolib", "flowWorkspace"))
#           shell: Rscript {0}  
#           run: |
#             git clone --depth 1 https://github.com/RGLab/flowWorkspace.git --branch master --single-branch
#           run: echo "test-gs-compatibility=yes" >> $GITHUB_ENV
#           run: |
#             devtools::test("flowWorkspace")
#           shell: Rscript {0}
#           run: rm -rf /tmp/gs  
      
      
