name: cytoverse-ci

on:
  push:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  rcheck:
    runs-on: ubuntu-latest
    outputs:
      cytolib_modified: ${{ steps.check_files.outputs.cytolib_modified }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name : generate gs
        run: |
          pwd
          ls
          mkdir gs
          cd gs
          echo 'test22' >> t.txt
          dd=gs
          echo 'tmp_gs_dir=$dd' >> $GITHUB_ENV
          echo $dd
      - name: Upload the test gs as the artifact
        uses: 'actions/upload-artifact@v2'
        with:
            name: my-artifact
            path: ${{ env.tmp_gs_dir }}
      - name: clean up temp gs
        run: rm -rf ${{ env.tmp_gs_dir }}

      - name: check modified cytolib files
        id: check_cytolib_files
        run: |

          # check internal repo
          if git diff --name-only HEAD^ HEAD | grep -q R/; then
            internal_modified = true
          else
            internal_modified = false
          fi
          
          # check public repo
          public_modified = false
          cd /tmp
          git clone https://github.com/mikejiang/testA.git
          cd testA
          if git diff --name-only HEAD^ HEAD | grep -q test.txt; then
            public_modified = true
          fi

          # set flag only if both public and internal are updated
          if [ public_modified == true ] || [ internal_modified == true ]; then
            echo "::set-output name=cytolib_modified::true"
          else
            echo "::set-output name=cytolib_modified::false"
          fi

  test-open-source:
      needs: rcheck
      runs-on: ubuntu-latest
      steps:
        # - name: Download the test gs from the artifact
        #   uses: actions/download-artifact@v2
        #   with:
        #     name: my-artifact
        #     path: /tmp/gs

        - name: Run the R tests against the test gs
          if: needs.rcheck.outputs.cytolib_modified== 'true'
#           run: |
#             BiocManager::install(c("cytolib", "flowWorkspace"))
#           shell: Rscript {0}  
#           run: |
#             git clone --depth 1 https://github.com/RGLab/flowWorkspace.git --branch master --single-branch
#           run: echo "test-gs-compatibility=yes" >> $GITHUB_ENV
#           run: |
#             devtools::test("flowWorkspace")
#           shell: Rscript {0}
          run: |
            echo "job2"      
