# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ r-4.0 ]
  pull_request:
    branches: [ r-4.0 ]

jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        r-version: [4.0]

    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@main
        with:
          r-version: ${{ matrix.r-version }}
      - name: build
        run: R CMD INSTALL --build .
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: https://uploads.github.com/repos/mikejiang/pkgA/releases/release
          asset_path: ./pkgA_0.1.0.tgz
          asset_name: pkgA_0.1.0.tgz
          asset_content_type: application/gzip
